"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS =config('ALLOWED_HOSTS', default='*').split(',')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Local apps
    'users.apps.UsersConfig',
    'resultados.apps.ResultadosConfig',
    'empresas.apps.EmpresasConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # CORS first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database Setup (PostgreSQL — BD propia del nuevo sistema)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# BD FASIL (MySQL 5.5) — Conexion directa via PyMySQL (solo lectura)
# NOTA: Django 5.x exige MySQL >= 8.0.11 pero FASIL corre MySQL 5.5.56.
# Por eso NO se registra en DATABASES — Django lo rechazaria.
# La conexion se hace con PyMySQL directo desde fasil_service.py.
FASIL_ENABLED = config('FASIL_ENABLED', default=False, cast=bool)
FASIL_DB_NAME = config('FASIL_DB_NAME', default='bioanalisis30')
FASIL_DB_USER = config('FASIL_DB_USER', default='fasil2')
FASIL_DB_PASSWORD = config('FASIL_DB_PASSWORD', default='')
FASIL_DB_HOST = config('FASIL_DB_HOST', default='192.168.1.109')
FASIL_DB_PORT = config('FASIL_DB_PORT', default='3306')
FASIL_BIRT_HOST = config('FASIL_BIRT_HOST', default='http://192.168.1.109:8080')
FASIL_BIRT_USER = config('FASIL_BIRT_USER', default='54')

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Media files (PDFs de resultados, etc.)
# Los PDFs se almacenan en el filesystem en vez de BLOB en la BD
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Max upload size: 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configurations
# M-04 Gap Analysis: paginación global para evitar listados O(n) sin límite.
# Todos los endpoints GET de listado retornarán máx PAGE_SIZE registros.
# Respuesta: { "count": N, "next": "?page=2", "previous": null, "results": [...] }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Paginación global — Acción 4 (M-04)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # Filtrado y ordenamiento — facilita búsquedas clínicas por nombre/fecha
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# JWT configurations
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTHORIZATION_HEADER_TYPES': ('Bearer',),
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True # In production this should be restricted
CORS_ALLOW_CREDENTIALS = True

# =============================================================================
# LOGGING — Acción 8 (M-06 Gap Analysis)
# =============================================================================
# Registra acciones críticas del sistema clínico para trazabilidad y auditoría.
# Contexto regulatorio: Ley 1581 (datos personales de salud en Colombia).
#
# Niveles usados:
#   - WARNING : eventos inesperados en el core de Django
#   - INFO    : acciones de negocio (login, carga resultado, toggle empresa)
#   - ERROR   : fallos no controlados en las apps del proyecto
#
# En producción, rotar audit.log con logrotate o similar.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        # Formato completo para el archivo de auditoría
        'audit': {
            'format': '[{asctime}] [{levelname}] [{name}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Formato simplificado para consola en desarrollo
        'consola': {
            'format': '{levelname} {name}: {message}',
            'style': '{',
        },
    },

    'handlers': {
        # Consola — siempre activo (útil en desarrollo y en Docker logs)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'consola',
        },
        # Archivo de auditoría — append, rotación manual o con logrotate
        'audit_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'audit.log',
            'formatter': 'audit',
            'encoding': 'utf-8',
        },
    },

    'loggers': {
        # Core Django — solo WARNING y superior (evita ruido de requests)
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Apps del proyecto — INFO+, va a consola Y a audit.log
        'users': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'empresas': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'resultados': {
            'handlers': ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
