version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: labclinic_postgres
    restart: always
    environment:
      POSTGRES_DB: labclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9988:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
