# Generated by Django 5.2.13 on 2026-05-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio (COP)')),
                ('categoria', models.CharField(choices=[('Coagulación', 'Coagulación'), ('Hematología', 'Hematología'), ('Hormonas', 'Hormonas'), ('Infectología', 'Infectología'), ('Inmunología', 'Inmunología'), ('Metabolismo', 'Metabolismo'), ('Microbiología', 'Microbiología'), ('Oncología', 'Oncología'), ('Otras', 'Otras'), ('Tiroides', 'Tiroides')], default='Otras', max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('sintomas', models.JSONField(default=list, verbose_name='Síntomas')),
                ('requiere_ayuno', models.BooleanField(default=False, verbose_name='Requiere ayuno')),
                ('preparacion', models.TextField(blank=True, verbose_name='Preparación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['nombre'],
            },
        ),
    ]
