# Generated by Django 6.0.3 on 2026-04-02 20:08

import django.db.models.deletion
import resultados.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('NIT', 'NIT')], default='CC', max_length=5, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('id_fasil', models.CharField(blank=True, help_text='Identificador del paciente en el sistema FASIL (para integración futura)', max_length=50, null=True, unique=True, verbose_name='ID en sistema FASIL')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(help_text='Ej: Hemograma, Perfil Lipídico, Uroanálisis', max_length=100, verbose_name='Tipo de examen')),
                ('fuente', models.CharField(choices=[('FASIL', 'Sistema FASIL'), ('EXTERNO', 'Laboratorio Externo'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', max_length=10, verbose_name='Fuente del resultado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de validación'), ('VALIDADO', 'Validado'), ('ENTREGADO', 'Entregado al paciente')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('archivo_pdf', models.FileField(help_text='Resultado en formato PDF', upload_to=resultados.models.resultado_upload_path, verbose_name='Archivo PDF')),
                ('tipo_archivo', models.CharField(default='application/pdf', max_length=50, verbose_name='Tipo MIME del archivo')),
                ('fecha_examen', models.DateField(verbose_name='Fecha del examen')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales del bacteriólogo', verbose_name='Observaciones')),
                ('id_orden_fasil', models.CharField(blank=True, help_text='Referencia a svc_ordenes en FASIL (para integración futura)', max_length=50, null=True, verbose_name='ID Orden FASIL')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='resultados.paciente', verbose_name='Paciente')),
                ('subido_por', models.ForeignKey(blank=True, help_text='Bacteriólogo o admin que cargó el resultado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-fecha_examen', '-fecha_carga'],
            },
        ),
    ]
