# Generated by Django 6.0.3 on 2026-04-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Si el resultado fue solicitado por una empresa cliente (B2B).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
