# Generated by Django 5.2.13 on 2026-04-26 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_paciente_user(apps, schema_editor):
    Resultado = apps.get_model('resultados', 'Resultado')
    for r in Resultado.objects.select_related('paciente__user').filter(
        paciente__isnull=False,
        paciente__user__isnull=False,
    ):
        r.paciente_user_id = r.paciente.user_id
        r.save(update_fields=['paciente_user_id'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_resultado_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='paciente_user',
            field=models.ForeignKey(blank=True, help_text='FK directa al User del paciente. Reemplaza la indirección via Paciente.user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_directos', to=settings.AUTH_USER_MODEL, verbose_name='Paciente (usuario)'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='resultados.paciente', verbose_name='Paciente'),
        ),
        migrations.RunPython(populate_paciente_user, reverse_populate),
    ]
