# Generated by Django 5.2.13 on 2026-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_resultado_paciente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='paciente_documento',
            field=models.CharField(blank=True, db_index=True, help_text='Documento cuando no existe Paciente en BD. Query por documento al registrarse.', max_length=20, null=True, verbose_name='Documento del paciente (lake)'),
        ),
    ]
