# Generated by Django 5.2.13 on 2026-05-16 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('REACTIVO', 'Reactivo'), ('CONSUMIBLE', 'Consumible'), ('MATERIAL_VIDRIO', 'Material de Vidrio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja'), ('ML', 'Mililitro'), ('LT', 'Litro'), ('GR', 'Gramo'), ('PAQUETE', 'Paquete')], max_length=10, verbose_name='Unidad de medida')),
                ('stock_actual', models.PositiveIntegerField(default=0, help_text='Solo se modifica via /ingreso/ y /egreso/.', verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Nivel mínimo de alerta.', verbose_name='Stock mínimo')),
                ('proveedor_habitual', models.CharField(blank=True, max_length=200, verbose_name='Proveedor habitual')),
                ('ultimo_costo', models.DecimalField(blank=True, decimal_places=2, help_text='Solo visible para admin.', max_digits=10, null=True, verbose_name='Último costo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('numero_lote', models.CharField(blank=True, max_length=100, verbose_name='Número de lote')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
