# Generated by Django 5.2.13 on 2026-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre completo'),
        ),
    ]
